[2024-07-07T15:06:17.891+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-07T15:06:17.978+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag.say_hello manual__2024-07-07T15:06:14.832820+00:00 [queued]>
[2024-07-07T15:06:17.991+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag.say_hello manual__2024-07-07T15:06:14.832820+00:00 [queued]>
[2024-07-07T15:06:17.991+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-07T15:06:18.035+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): say_hello> on 2024-07-07 15:06:14.832820+00:00
[2024-07-07T15:06:18.065+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=144445) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-07T15:06:18.067+0000] {standard_task_runner.py:63} INFO - Started process 144455 to run task
[2024-07-07T15:06:18.068+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'say_hello', 'manual__2024-07-07T15:06:14.832820+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmpx5lhc6ed']
[2024-07-07T15:06:18.075+0000] {standard_task_runner.py:91} INFO - Job 48: Subtask say_hello
[2024-07-07T15:06:18.167+0000] {task_command.py:426} INFO - Running <TaskInstance: my_first_dag.say_hello manual__2024-07-07T15:06:14.832820+00:00 [running]> on host 64c03b0d339f
[2024-07-07T15:06:18.295+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_first_dag' AIRFLOW_CTX_TASK_ID='say_hello' AIRFLOW_CTX_EXECUTION_DATE='2024-07-07T15:06:14.832820+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-07T15:06:14.832820+00:00'
[2024-07-07T15:06:18.297+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-07T15:06:18.298+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-07T15:06:18.298+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/my_first_dag.py", line 9, in _say_hello
    logging.debug("This is DEBUG log")
    ^^^^^^^
NameError: name 'logging' is not defined. Did you forget to import 'logging'
[2024-07-07T15:06:18.312+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=my_first_dag, task_id=say_hello, run_id=manual__2024-07-07T15:06:14.832820+00:00, execution_date=20240707T150614, start_date=20240707T150617, end_date=20240707T150618
[2024-07-07T15:06:18.327+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 48 for task say_hello (name 'logging' is not defined; 144455)
[2024-07-07T15:06:18.364+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-07T15:06:18.387+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-07T15:06:18.395+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
