[2024-07-22T13:41:16.525+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-22T13:41:16.549+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: neon_pj.rename_column manual__2024-07-22T13:36:00.537938+00:00 [queued]>
[2024-07-22T13:41:16.554+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: neon_pj.rename_column manual__2024-07-22T13:36:00.537938+00:00 [queued]>
[2024-07-22T13:41:16.554+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-22T13:41:16.568+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): rename_column> on 2024-07-22 13:36:00.537938+00:00
[2024-07-22T13:41:16.577+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'neon_pj', 'rename_column', 'manual__2024-07-22T13:36:00.537938+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/neon_pj.py', '--cfg-path', '/tmp/tmppseregi9']
[2024-07-22T13:41:16.579+0000] {standard_task_runner.py:91} INFO - Job 6: Subtask rename_column
[2024-07-22T13:41:16.581+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=39970) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-22T13:41:16.582+0000] {standard_task_runner.py:63} INFO - Started process 39977 to run task
[2024-07-22T13:41:16.618+0000] {task_command.py:426} INFO - Running <TaskInstance: neon_pj.rename_column manual__2024-07-22T13:36:00.537938+00:00 [running]> on host 3c53d9be62d8
[2024-07-22T13:41:16.699+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='neon_pj' AIRFLOW_CTX_TASK_ID='rename_column' AIRFLOW_CTX_EXECUTION_DATE='2024-07-22T13:36:00.537938+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-22T13:36:00.537938+00:00'
[2024-07-22T13:41:16.701+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-22T13:41:16.702+0000] {sql.py:276} INFO - Executing: 
            create or replace view staging_chickens
            as
                select
                    year,
                    province,
                    valu as number_of_chickens
            from chickens
            
[2024-07-22T13:41:16.708+0000] {base.py:84} INFO - Using connection ID 'neon_pj' for task execution.
[2024-07-22T13:41:16.713+0000] {base.py:84} INFO - Using connection ID 'neon_pj' for task execution.
[2024-07-22T13:41:16.801+0000] {sql.py:487} INFO - Running statement: 
            create or replace view staging_chickens
            as
                select
                    year,
                    province,
                    valu as number_of_chickens
            from chickens
            , parameters: None
[2024-07-22T13:41:16.811+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-22T13:41:16.812+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 435, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 492, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "valu" does not exist
LINE 7:                     valu as number_of_chickens
                            ^
HINT:  Perhaps you meant to reference the column "chickens.value".

[2024-07-22T13:41:16.820+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=neon_pj, task_id=rename_column, run_id=manual__2024-07-22T13:36:00.537938+00:00, execution_date=20240722T133600, start_date=20240722T134116, end_date=20240722T134116
[2024-07-22T13:41:16.834+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 6 for task rename_column (column "valu" does not exist
LINE 7:                     valu as number_of_chickens
                            ^
HINT:  Perhaps you meant to reference the column "chickens.value".
; 39977)
[2024-07-22T13:41:16.876+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-22T13:41:16.890+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-22T13:41:16.898+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
